#pragma once

// Debug
#define DEBUG_DRAW_TILES
#define DEBUG_DRAW_CHARACTER_BOXES
#define DEBUG_DRAW_KOOPA_BASE

//#define DEBUG_AUDIO_DISABLE_ALL
#define DEBUG_AUDIO_DISABLE_MUSIC
//#define DEBUG_AUDIO_DISABLE_SFX

#ifdef DEBUG_AUDIO_DISABLE_ALL
    #define DEBUG_AUDIO_DISABLE_MUSIC
    #define DEBUG_AUDIO_DISABLE_SFX
#endif
